[package]
name = "simple-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"
local-ip-address = "0.5.6"
tokio = { version = "1.35.1", features = ["full"] }
